name 'aergia'
maintainer 'Jiaqi Liu'
maintainer_email 'jack20191124@proton.me'
license 'Apache-2.0'
license 'all rights reserved'
description 'IaC recipes'
version '0.1.0'
chef_version '>= 16.0'
issues_url 'https://github.com/QubitPi/aergia/issues'
source_url 'https://github.com/QubitPi/aergia'
