build_source        = "docker.ubuntu"
image_home_dir      = "/"
ssl_cert_source     = "../../../tests/fullchain.pem.test"
ssl_cert_key_source = "../../../tests/privkey.pem.test"
base_domain         = "mycompany.com"
