build_source                     = "docker.ubuntu"
image_home_dir                   = "/"
aws_kong_ssl_cert_file_path      = "../../../tests/fullchain.pem.test"
aws_kong_ssl_cert_key_file_path  = "../../../tests/privkey.pem.test"
aws_kong_nginx_config_file_path  = "../../../tests/nginx.conf.test"
