build_source            = "docker.ubuntu"
image_home_dir          = "/"
kong_api_gateway_domain = "gateway.mycompany.com"
ssl_cert_key_source     = "../../../tests/privkey.pem.test"
ssl_cert_source         = "../../../tests/fullchain.pem.test"
