build_source                     = "docker.ubuntu"
image_home_dir                   = "/"
ws_war_path                      = "test-webservice-1.0-SNAPSHOT.war"
aws_ws_ssl_cert_file_path        = "../../../../tests/fullchain.pem.test"
aws_ws_ssl_cert_key_file_path    = "../../../../tests/privkey.pem.test"
aws_ws_nginx_config_file_path    = "../../../../tests/nginx.conf.test"
aws_ws_filebeat_config_file_path = "filebeat.yml"
