# Copyright Jiaqi Liu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: Slack Notification

"on":
  workflow_call:
    inputs:
      job-status:
        description: |
          The current status of the job, which determines the "entire job status" in the Slack message, from caller workflow.
          Possible values are "success", "failure", ""(skipped), or "cancelled".
        type: string
        required: true
    secrets:
      slack-webhook-url:
        description: |
          A standard Slack Webhook URL that connects to a Slack channel.
          This is the same thing as "SLACK_WEBHOOK_URL"; please see
          https://github.com/marketplace/actions/slack-send#technique-3-slack-incoming-webhook
          for more info
        required: true

jobs:
  slack-notification:
    name: Send GitHub Action results to Slack Specified Channel
    runs-on: ubuntu-latest
    steps:
      - name: Send GitHub Action result to a specified Slack if build succeeded
        if: ${{ inputs.job-status == 'success' }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "GitHub Action ${{ github.event.repository.name }} ${{ github.event.pull_request.title || github.event.head_commit.message }}: ${{ inputs.job-status }} ✅",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Build result of GitHub Action ${{ github.event.repository.name }} ${{ github.event.pull_request.title || github.event.head_commit.message }}: ${{ inputs.job-status }} ✅\nFiles changed: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack-webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Send GitHub Action result to a specified Slack if build failed
        if: ${{ inputs.job-status != 'success' }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "GitHub Action ${{ github.event.repository.name }}/${{ github.event.pull_request.title || github.event.head_commit.message }}: ${{ inputs.job-status || 'failure' }} ❌",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Build result of GitHub Action ${{ github.event.repository.name }}/${{ github.event.pull_request.title || github.event.head_commit.message }}: ${{ inputs.job-status || 'failure' }} ❌\nRun: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\nFiles changed: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.slack-webhook-url }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
